/**
 * All user-facing copy lives here (build brief §14) — English only in v1,
 * but nothing is hardcoded inline in a screen.
 */
export const strings = {
  common: {
    continue: 'Continue',
    skip: 'Skip',
    cancel: 'Cancel',
    done: 'Done',
    back: 'Back',
    retry: 'Try again',
    loadError: "We couldn't load this case.",
  },
  legal: {
    disclaimer: 'Pending is not a law firm and does not provide legal advice.',
    notAffiliated: 'Pending is not affiliated with USCIS or any government agency.',
  },
  auth: {
    title: 'Track your case, calmly.',
    subtitle: 'Sign in with your email. No password to remember or leak.',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    sendLink: 'Send me a link',
    sending: 'Sending…',
    checkEmailTitle: 'Check your email',
    checkEmailBody: 'We sent a sign-in link to {email}. Open it on this device to continue.',
    useDifferentEmail: 'Use a different email',
    invalidEmail: 'Enter a valid email address.',
    genericError: 'Something went wrong sending your link. Try again.',
    signingIn: 'Signing you in…',
    callbackError: "That link didn't work. Request a new one.",
  },
  onboarding: {
    stepOf: 'Step {current} of {total}',
    receipt: {
      title: 'Add your case',
      subtitle: 'Enter the 13-character receipt number from your notice.',
      label: 'Receipt number',
      placeholder: 'IOE0912345678',
      invalidFormat: "That doesn't look like a receipt number. It's 3 letters and 10 digits.",
      checking: 'Checking…',
      checkedTitle: 'Found it',
      unavailable: "We couldn't check your status right now. You can still add this case.",
      notFound: "We couldn't find a case with that receipt number.",
      duplicateTitle: 'Already tracking this case',
      duplicateBody: 'This receipt number is already in your list.',
      openExisting: 'Open it',
    },
    formType: {
      label: 'What kind of case is this?',
    },
    filingDate: {
      title: 'When did you file?',
      subtitle: 'The date printed on your receipt notice.',
      label: 'Filing date',
    },
    zip: {
      title: 'Which office handles your case?',
      subtitle:
        "USCIS assigns your case to a field office based on your address. Enter your ZIP code and we'll figure out the rest — we don't store the ZIP itself, only the office.",
      label: 'ZIP code',
      skip: "I don't know / skip",
    },
    milestones: {
      title: 'Has any of this already happened?',
      subtitle: 'Optional — add dates for anything already behind you.',
      biometrics: 'Biometrics appointment',
      interviewScheduled: 'Interview scheduled',
      interviewed: 'Interviewed',
      rfe: 'Received a request for evidence',
    },
    notifications: {
      title: 'Stay in the loop',
      subtitle: "We'll notify you the moment your status changes. No spam, ever.",
      enable: 'Enable notifications',
      skip: 'Not now',
      finishing: 'Setting up your case…',
    },
  },
  home: {
    daysLabel: 'days',
    waitingLabel: 'waiting',
    rulerInRange: 'Still inside the normal range for this office.',
    rulerPastRange: 'This case has passed the typical range for this office.',
    rulerYou: 'YOU',
    rulerAccessibilityLabel: '{days} days, typical range {low} to {high} days',
    checkedJustNow: 'Checked just now',
    checkedAgo: 'Checked {time} ago',
    shareTimeline: 'Share timeline',
    // Placeholder — replace with the real domain before shipping.
    shareDomain: 'pending.app',
    shareDaysWaiting: 'days waiting',
    legalDisclaimer: 'Pending is not a law firm and does not provide legal advice.',
    decidedApproved: 'Approved',
    decidedDenied: 'Decision received',
  },
  timeline: {
    kindLabels: {
      filed: 'Case filed',
      biometrics_scheduled: 'Biometrics scheduled',
      biometrics: 'Biometrics appointment',
      interview_scheduled: 'Interview scheduled',
      interview: 'Interview',
      rfe: 'Request for evidence',
      rfe_manual: 'RFE response due',
      transferred: 'Case transferred',
      decision: 'Decision',
      card_mailed: 'Card mailed',
      other: 'Update',
    },
    inDays: 'in {days} days',
    inOneDay: 'in 1 day',
    today: 'today',
    daysAgo: '{days} days ago',
    oneDayAgo: '1 day ago',
  },
  cases: {
    title: 'Your cases',
    addCase: 'Add a case',
    daysSuffix: 'd',
  },
  settings: {
    title: 'Settings',
    notifications: 'Notifications',
    notificationsSubtitle: 'Get a push the moment your status changes.',
    removeCase: 'Remove this case',
    removeCaseConfirmTitle: 'Remove {label}?',
    removeCaseConfirmBody: 'This deletes its history from Pending. This cannot be undone.',
    exportData: 'Export my data',
    deleteAccount: 'Delete account',
    deleteAccountConfirmTitle: 'Delete your account?',
    deleteAccountConfirmBody: 'This immediately and permanently deletes every case, timeline, and reminder. This cannot be undone.',
    cancel: 'Cancel',
    confirm: 'Delete',
    signOut: 'Sign out',
  },
  menu: {
    allCases: 'All cases',
    settings: 'Settings',
  },
  pendingDetails: {
    interview_date: {
      question: 'Your interview was scheduled.',
      prompt: 'Add the date so we can remind you.',
    },
    biometrics_date: {
      question: 'Your biometrics appointment was scheduled.',
      prompt: 'Add the date so we can remind you.',
    },
    notice_mailed: {
      question: 'USCIS mailed you a notice.',
      prompt: 'Which notice was it?',
    },
    rfe_deadline: {
      question: 'USCIS requested additional evidence.',
      prompt: 'Add the response deadline printed on the notice.',
    },
    office_reresolve: {
      question: 'Your case was transferred to a new office.',
      prompt: "Enter your ZIP again so we can update your case's office.",
    },
    save: 'Save',
    dismiss: 'Not now',
    noticeChips: {
      approval: 'Approval notice',
      rfeNotice: 'RFE notice',
      transferNotice: 'Transfer notice',
      biometricsNotice: 'Biometrics notice',
      interviewNotice: 'Interview notice',
      other: 'Other',
    },
  },
} as const;
