/**
 * All user-facing copy lives here (build brief §14) — English only in v1,
 * but nothing is hardcoded inline in a screen.
 */
export const strings = {
  common: {
    continue: 'Continue',
    skip: 'Skip',
    cancel: 'Cancel',
    done: 'Done',
    back: 'Back',
    retry: 'Try again',
    loadError: "We couldn't load this case.",
  },
  legal: {
    disclaimer: 'Pending is not a law firm and does not provide legal advice.',
    notAffiliated: 'Pending is not affiliated with USCIS or any government agency.',
  },
  auth: {
    title: 'Track your case, calmly.',
    subtitle: 'Sign in with a one-time code. No password to remember or leak.',
    methodEmail: 'Email',
    methodPhone: 'Phone',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    phoneLabel: 'Phone number',
    phonePlaceholder: '+1 555 010 1234',
    sendCode: 'Send me a code',
    sending: 'Sending…',
    codeTitle: 'Enter your code',
    codeBodyEmail: 'We sent a 6-digit code to {contact}.',
    codeBodyPhone: 'We texted a 6-digit code to {contact}.',
    codeLabel: 'Code',
    codePlaceholder: '123456',
    verify: 'Verify',
    verifying: 'Verifying…',
    useDifferentContact: 'Use a different email or phone',
    resendCode: 'Resend code',
    invalidEmail: 'Enter a valid email address.',
    invalidPhone: 'Enter a phone number with country code, e.g. +1 555 010 1234.',
    invalidCode: 'Enter the 6-digit code.',
    genericError: 'Something went wrong sending your code. Try again.',
    wrongCode: "That code didn't work. Check it and try again.",
  },
  biometricLock: {
    title: 'Unlock Pending',
    subtitle: 'Use Face ID or Touch ID to continue.',
    unlock: 'Unlock',
    failed: "That didn't work. Try again.",
  },
  onboarding: {
    stepOf: 'Step {current} of {total}',
    receipt: {
      title: 'Add your case',
      subtitle: 'Enter the 13-character receipt number from your notice.',
      label: 'Receipt number',
      placeholder: 'IOE0912345678',
      invalidFormat: "That doesn't look like a receipt number. It's 3 letters and 10 digits.",
      checking: 'Checking…',
      checkedTitle: 'Found it',
      unavailable: "We couldn't check your status right now. You can still add this case.",
      notFound: "We couldn't find a case with that receipt number.",
      duplicateTitle: 'Already tracking this case',
      duplicateBody: 'This receipt number is already in your list.',
      openExisting: 'Open it',
    },
    formType: {
      label: 'What kind of case is this?',
    },
    filingDate: {
      title: 'When did you file?',
      subtitle: 'The date printed on your receipt notice.',
      label: 'Filing date',
    },
    zip: {
      title: 'Which office handles your case?',
      subtitle:
        "USCIS assigns your case to a field office based on your address. Enter your ZIP code and we'll figure out the rest — we don't store the ZIP itself, only the office.",
      label: 'ZIP code',
      skip: "I don't know / skip",
    },
    milestones: {
      title: 'Has any of this already happened?',
      subtitle: 'Optional — add dates for anything already behind you.',
      biometrics: 'Biometrics appointment',
      interviewScheduled: 'Interview scheduled',
      interviewed: 'Interviewed',
      rfe: 'Received a request for evidence',
    },
    notifications: {
      title: 'Stay in the loop',
      subtitle: "We'll notify you the moment your status changes. No spam, ever.",
      enable: 'Enable notifications',
      skip: 'Not now',
      finishing: 'Setting up your case…',
    },
  },
  home: {
    daysLabel: 'days',
    waitingLabel: 'waiting',
    rulerInRange: 'Still inside the normal range for this office.',
    rulerPastRange: "Past the typical range for this office — that alone doesn't mean anything is wrong. Processing times vary case by case.",
    rulerYou: 'YOU',
    rulerAccessibilityLabel: '{days} days, typical range {low} to {high} days',
    stageEstimate: 'Based on {count} similar cases, a decision typically follows by around {date}.',
    stageEstimateTypical: "Based on this office's typical range, a decision usually follows by around {date}.",
    checkedJustNow: 'Checked just now',
    checkedAgo: 'Checked {time} ago',
    shareTimeline: 'Share timeline',
    // Placeholder — replace with the real domain before shipping.
    shareDomain: 'pending.app',
    shareDaysWaiting: 'days waiting',
    legalDisclaimer: 'Pending is not a law firm and does not provide legal advice.',
    decidedApproved: 'Approved',
    decidedDenied: 'Decision received',
  },
  timeline: {
    kindLabels: {
      filed: 'Case filed',
      biometrics_scheduled: 'Biometrics scheduled',
      biometrics: 'Biometrics appointment',
      interview_scheduled: 'Interview scheduled',
      interview: 'Interview',
      rfe: 'Request for evidence',
      rfe_manual: 'RFE response due',
      transferred: 'Case transferred',
      decision: 'Decision',
      card_mailed: 'Card mailed',
      other: 'Update',
    },
    inDays: 'in {days} days',
    inOneDay: 'in 1 day',
    today: 'today',
    daysAgo: '{days} days ago',
    oneDayAgo: '1 day ago',
  },
  cases: {
    title: 'Your cases',
    addCase: 'Add a case',
    daysSuffix: 'd',
  },
  settings: {
    title: 'Settings',
    notifications: 'Notifications',
    notificationsSubtitle: 'Get a push the moment your status changes.',
    biometricLock: 'Require Face ID',
    biometricLockSubtitle: 'Unlock Pending with Face ID or Touch ID instead of signing in again.',
    removeCase: 'Remove this case',
    removeCaseConfirmTitle: 'Remove {label}?',
    removeCaseConfirmBody: 'This deletes its history from Pending. This cannot be undone.',
    exportData: 'Export my data',
    deleteAccount: 'Delete account',
    deleteAccountConfirmTitle: 'Delete your account?',
    deleteAccountConfirmBody: 'This immediately and permanently deletes every case, timeline, and reminder. This cannot be undone.',
    cancel: 'Cancel',
    confirm: 'Delete',
    signOut: 'Sign out',
  },
  menu: {
    allCases: 'All cases',
    settings: 'Settings',
  },
  pendingDetails: {
    interview_date: {
      question: 'Your interview was scheduled.',
      prompt: 'Add the date so we can remind you.',
    },
    biometrics_date: {
      question: 'Your biometrics appointment was scheduled.',
      prompt: 'Add the date so we can remind you.',
    },
    notice_mailed: {
      question: 'USCIS mailed you a notice.',
      prompt: 'Which notice was it?',
    },
    rfe_deadline: {
      question: 'USCIS requested additional evidence.',
      prompt: 'Add the response deadline printed on the notice.',
    },
    office_reresolve: {
      question: 'Your case was transferred to a new office.',
      prompt: "Enter your ZIP again so we can update your case's office.",
    },
    save: 'Save',
    dismiss: 'Not now',
    noticeChips: {
      approval: 'Approval notice',
      rfeNotice: 'RFE notice',
      transferNotice: 'Transfer notice',
      biometricsNotice: 'Biometrics notice',
      interviewNotice: 'Interview notice',
      other: 'Other',
    },
  },
} as const;
